site_name: 'ProNouns Docs'

copyright: "Copyright © Lucy Poulton 2021. All rights reserved."

theme:
  name: "mkdocs"
  hljs_style: "darcula"

extra_css:
  - stylesheets/lucy.css

nav:
  - Index: index.md
  - Setup: setup.md
  - Placeholders: papi.md
  - Formats: formats.md